[tools]
node = "22.16.0"
"npm:@anthropic-ai/claude-code" = "latest"
pnpm = "latest"

[env]
_.path = ['./node_modules/.bin']
_.file = ".env"
CLOUDFLARE_DATABASE_ID = "95084f46-59b0-441c-9300-33651a2bf018"
