name: CI and CD
on:
  push:
    branches:
      - main
jobs:
  ci:
    uses: clov3r-cc/turn-on-air-conditioner/.github/workflows/ci.yaml@main
  cd:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - ci
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js with Volta
        uses: ./.github/actions/setup-node
      - name: Publish
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          command: deploy
          secrets: |
            NODE_ENV
            SWITCHBOT_TOKEN
            SWITCHBOT_CLIENT_SECRET
            SENTRY_CLIENT_ID
            SENTRY_CLIENT_SECRET
            NOTIFICATION_WEBHOOK_URL
        env:
          NODE_ENV: production
          SWITCHBOT_TOKEN: ${{ secrets.SWITCHBOT_TOKEN }}
          SWITCHBOT_CLIENT_SECRET: ${{ secrets.SWITCHBOT_CLIENT_SECRET }}
          SENTRY_CLIENT_ID: ${{ secrets.SENTRY_CLIENT_ID }}
          SENTRY_CLIENT_SECRET: ${{ secrets.SENTRY_CLIENT_SECRET }}
          NOTIFICATION_WEBHOOK_URL: ${{ secrets.NOTIFICATION_WEBHOOK_URL }}
